//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by sagestudio.rc
//
#define IDI_SAGESTUDIO                  101
#define IDR_MAIN_WIN_MENU               102
#define IDR_MAIN_WIN_ACCEL              103
#define IDD_GAMEMANAGER_DIALOGBAR       103
#define IDD_STATEMACHINE_DIALOGBAR      104
#define IDD_GETTEXT_DIALOG              105
#define IDC_INSERT_ENTRY_CURSOR         105
#define IDR_GAME_MANAGER_POPUP          106
#define IDC_INSERT_EXIT_CURSOR          106
#define IDD_CONTENTDIRECTORY_DIALOG     107
#define IDC_INSERT_STATE_CURSOR         107
#define IDC_INSERT_EVENT_CURSOR         108
#define IDD_RESOURCECONTEXT_DIALOGBAR   109
#define IDD_IMAGE_PROPS_DIALOGBAR       110
#define IDD_IMAGE_TOOLS_DIALOGBAR       111
#define IDD_CREATINGTHUMBNAILS          112
#define IDR_STATE_MACHINE_MENU          114
#define IDD_STATE_NODE_PROPERTIES       118
#define IDD_EVENT_PROPERTIES            119
#define IDD_COMMAND_DIALOG              121
#define IDD_CHOOSEIMAGE_DIALOG          122
#define IDD_CHOOSESOUND_DIALOG          123
#define IDD_CHOOSEMUSIC_DIALOG          124
#define IDD_CHOOSERESOURCECONTEXT_DIALOG 125
#define IDD_2DCELLMAP_VIEW_DIALOGBAR    127
#define IDD_2DCELLMAP_PROPS_DIALOGBAR   128
#define IDD_DIALOG1                     129
#define IDD_CHOOSECELLMAP_DIALOG        129
#define IDD_GAME_PROPERTIES_DIALOG      130
#define IDD_DEFAULTBINDINGS_DIALOGBAR   131
#define IDD_DIALOG2                     132
#define IDD_CHOOSEBINDCOMMAND_DIALOG    132
#define IDD_CAMERA_PROPERTIES           133
#define IDD_CHOOSECAMERA_DIALOG         134
#define IDD_CHOOSECELLTYPE_DIALOG       135
#define IDD_TEXTURESET_DIALOGBAR        136
#define IDD_TEXTURESETMANAGER_DIALOGBAR 139
#define IDD_CHOOSETEXTURE_DIALOG        140
#define IDD_CHOOSETEXTURESET_DIALOG     141
#define IDD_BINDINGOPENGLIMAGES_DIALOG  142
#define IDD_TEXTURESETPROPERTIES_DIALOG 143
#define IDD_SKY_DIALOGBAR               144
#define IDD_LOADMAPPROGRESS_DIALOG      145
#define IDD_SAVEMAPPROGRESS_DIALOG      146
#define IDD_LIGHTS_DIALOGBAR            147
#define IDD_LIGHTINGPROGRESS_DIALOG     148
#define IDC_GAME_TREE                   1001
#define IDC_INSERT_ENTRY                1003
#define IDC_INSERT_EXIT                 1004
#define IDC_TEXT                        1004
#define IDC_INSERT_STATE                1005
#define IDC_LABEL                       1005
#define IDC_INSERT_EVENT                1006
#define IDC_MOVE                        1007
#define IDC_DELETE                      1008
#define IDC_PROPERTIES                  1009
#define IDC_TOOL_LABEL                  1010
#define IDC_CHOOSECONTENTDIRECTORY      1011
#define IDC_CONTENTDIRECTORY            1012
#define IDC_CONTENTTYPE                 1013
#define IDC_ADDFILE                     1014
#define IDC_DELETEFILE                  1015
#define IDC_DELETEALLFILES              1016
#define IDC_ADDDIRECTORY                1017
#define IDC_FILES                       1018
#define IDC_PLAYFILE                    1019
#define IDC_STOPFILE                    1020
#define IDC_SHOWIMAGETHUMBNAILS         1021
#define IDC_LIST1                       1022
#define IDC_ODTEXTURES                  1022
#define IDC_RESOURCES                   1022
#define IDC_TEXTURES                    1022
#define IDC_IMAGES                      1022
#define IDC_CELLTYPE                    1022
#define IDC_TEXTURESETS                 1022
#define IDC_LIGHTS                      1022
#define IDC_MANAGE                      1023
#define IDC_TEXTURESET                  1023
#define IDC_MOVE1LEFT                   1024
#define IDC_MOVEALLLEFT                 1025
#define IDC_MOVE1RIGHT                  1026
#define IDC_MOVEALLRIGHT                1027
#define IDC_RESOURCETYPE                1028
#define IDC_ODRESOURCES                 1029
#define IDC_FRAMEX                      1030
#define IDC_FRAMEY                      1031
#define IDC_FRAMEW                      1032
#define IDC_FRAMEH                      1033
#define IDC_FRAMECOUNT                  1034
#define IDC_MOUSEACTION                 1035
#define IDC_LABELFRAMEX                 1036
#define IDC_LABELFRAMEY                 1037
#define IDC_LABELFRAMEW                 1038
#define IDC_LABELFRAMEH                 1039
#define IDC_LABELFRAMECOUNT             1040
#define IDC_LABELMOUSEACTION            1041
#define IDC_APPLYPOS                    1042
#define IDC_APPLYSIZE                   1043
#define IDC_ZOOM                        1043
#define IDC_APPLYSIZE2                  1044
#define IDC_APPLYFRAMECOUNT             1044
#define IDC_TOOL                        1044
#define IDC_ENABLEGRIDSNAP              1045
#define IDC_GRIDSNAP                    1046
#define IDC_APPLY                       1047
#define IDC_PROGRESS1                   1050
#define IDC_PROGRESS2                   1051
#define IDC_PROGRESS3                   1052
#define IDC_REMOVE                      1052
#define IDC_INSERT                      1054
#define IDC_CLEARALL                    1055
#define IDC_SELECT                      1056
#define IDC_NAME                        1057
#define IDC_EVENTS                      1058
#define IDC_COMMANDS                    1059
#define IDC_EDIT                        1061
#define IDC_COMMANDTYPE                 1066
#define IDC_LINKAREA                    1067
#define IDC_SOUNDS                      1068
#define IDC_MUSIC                       1069
#define IDC_RESOURCECONTEXTS            1070
#define IDC_SHOWGRID                    1071
#define IDC_VIEWSTYLE                   1072
#define IDC_EDITMODE                    1073
#define IDC_MAPS                        1073
#define IDC_ZOOMLEVEL                   1074
#define IDC_STATEMACHINE                1076
#define IDC_CLEARBACKBUFFER             1077
#define IDC_BINDINGS                    1078
#define IDC_SET                         1079
#define IDC_CLEAR                       1080
#define IDC_BINDCOMMANDS                1082
#define IDC_POS_X                       1084
#define IDC_POS_Y                       1085
#define IDC_CAMERAS                     1085
#define IDC_POS_Z                       1086
#define IDC_BRUSH                       1086
#define IDC_ROT_X                       1087
#define IDC_SELECTNONE                  1087
#define IDC_ROT_Y                       1088
#define IDC_SETCELLTYPE                 1088
#define IDC_ROT_Z                       1089
#define IDC_SETTEXTURESET               1089
#define IDC_SELECTEDCELLS_GROUPBOX      1090
#define IDC_RED                         1098
#define IDC_LIQUIDCOLOR_LABEL           1099
#define IDC_RED_LABEL                   1100
#define IDC_GREEN_LABEL                 1101
#define IDC_BLUE_LABEL                  1102
#define IDC_GREEN                       1103
#define IDC_PROGRESS                    1103
#define IDC_BLUE                        1104
#define IDC_DEFAULTTEXTURESET           1104
#define IDC_MOVEUP                      1105
#define IDC_MOVEDOWN                    1106
#define IDC_COMBO1                      1108
#define IDC_RESCXT                      1108
#define IDC_CURRENTBRUSH                1108
#define IDC_CHOOSE                      1110
#define IDC_STATIC1                     1110
#define IDC_STATIC2                     1111
#define IDC_STATIC3                     1112
#define IDC_CURRENTTOOL                 1115
#define IDC_LIGHTRADIUSLABEL            1116
#define IDC_LIGHTRADIUS                 1117
#define IDC_USEWORLD                    1118
#define IDC_SPECIFY                     1119
#define IDC_AMBIENTLIGHT                1120
#define IDC_SETSPECIFIC                 1121
#define IDC_VIEWLIGHT                   1122
#define IDC_SETLIGHTCOLOR               1123
#define IDC_CALCULATELIGHTING           1124
#define IDC_AMBIENTWORLD                1135
#define IDC_SETWORLD                    1136
#define IDC_SETLIGHTRADIUS              1137
#define ID_FILE_NEW40001                40001
#define ID_FILE_OPEN40002               40002
#define ID_FILE_SAVE40003               40003
#define ID_FILE_SAVEAS                  40004
#define ID_FILE_CLOSE40005              40005
#define ID_FILE_EXIT                    40006
#define ID_EDIT_UNDO40007               40007
#define ID_EDIT_REDO40008               40008
#define ID_EDIT_CUT40009                40009
#define ID_EDIT_COPY40010               40010
#define ID_EDIT_PASTE40011              40011
#define ID_EDIT_DELETE                  40012
#define ID_EDIT_PROPERTIES              40013
#define ID_EDIT_INSERT                  40016
#define ID_GAMEMANAGERPOPUP_INSERT      40017
#define ID_GAMEMANAGERPOPUP_REMOVE      40018
#define ID_GAMEMANAGERPOPUP_PROPERTIES  40019
#define ID_VIEW_CONTENTDIRECTORYMANAGER 40033
#define ID_INSERT_ENTRYNODE             40036
#define ID_INSERT_EXITNODE              40037
#define ID_INSERT_STATENODE             40038
#define ID_INSERT_EVENT                 40039
#define ID_EDIT_INSERT40040             40040
#define ID_EDIT_REMOVE                  40041
#define ID_EDIT_PROPERTIES40042         40042
#define ID_INSERT_ENTRYNODE40043        40043
#define ID_INSERT_EXITNODE40044         40044
#define ID_INSERT_STATENODE40045        40045
#define ID_INSERT_EVENT40046            40046
#define ID_EDIT_SELECT                  40047
#define ID_VIEW_TEXTURESETMANAGER       40048
#define ID_FILE_COMPILEALLMAPS          40051
#define ID_CELLMAP_INSERT               40052
#define ID_CELLMAP_REMOVE               40053
#define ID_CELLMAP_PROPERTIES           40054
#define ID_CELLMAP_COMPILEALL           40055
#define ID_CELLMAP_COMPILE              40056

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        149
#define _APS_NEXT_COMMAND_VALUE         40057
#define _APS_NEXT_CONTROL_VALUE         1125
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
